/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateMeasureArgs } from "./CreateMeasureArgs";
import { UpdateMeasureArgs } from "./UpdateMeasureArgs";
import { DeleteMeasureArgs } from "./DeleteMeasureArgs";
import { MeasureFindManyArgs } from "./MeasureFindManyArgs";
import { MeasureFindUniqueArgs } from "./MeasureFindUniqueArgs";
import { Measure } from "./Measure";
import { LossFindManyArgs } from "../../loss/base/LossFindManyArgs";
import { Loss } from "../../loss/base/Loss";
import { SzenarioFindManyArgs } from "../../szenario/base/SzenarioFindManyArgs";
import { Szenario } from "../../szenario/base/Szenario";
import { MeasureService } from "../measure.service";

@graphql.Resolver(() => Measure)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class MeasureResolverBase {
  constructor(
    protected readonly service: MeasureService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Measure",
    action: "read",
    possession: "any",
  })
  async _measuresMeta(
    @graphql.Args() args: MeasureFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Measure])
  @nestAccessControl.UseRoles({
    resource: "Measure",
    action: "read",
    possession: "any",
  })
  async measures(
    @graphql.Args() args: MeasureFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Measure[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Measure",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Measure, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Measure",
    action: "read",
    possession: "own",
  })
  async measure(
    @graphql.Args() args: MeasureFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Measure | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Measure",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Measure)
  @nestAccessControl.UseRoles({
    resource: "Measure",
    action: "create",
    possession: "any",
  })
  async createMeasure(
    @graphql.Args() args: CreateMeasureArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Measure> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Measure",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Measure"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Measure)
  @nestAccessControl.UseRoles({
    resource: "Measure",
    action: "update",
    possession: "any",
  })
  async updateMeasure(
    @graphql.Args() args: UpdateMeasureArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Measure | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Measure",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Measure"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Measure)
  @nestAccessControl.UseRoles({
    resource: "Measure",
    action: "delete",
    possession: "any",
  })
  async deleteMeasure(
    @graphql.Args() args: DeleteMeasureArgs
  ): Promise<Measure | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Loss])
  @nestAccessControl.UseRoles({
    resource: "Measure",
    action: "read",
    possession: "any",
  })
  async loss(
    @graphql.Parent() parent: Measure,
    @graphql.Args() args: LossFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Loss[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Loss",
    });
    const results = await this.service.findLoss(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => [Szenario])
  @nestAccessControl.UseRoles({
    resource: "Measure",
    action: "read",
    possession: "any",
  })
  async szenario(
    @graphql.Parent() parent: Measure,
    @graphql.Args() args: SzenarioFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Szenario[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Szenario",
    });
    const results = await this.service.findSzenario(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }
}
