/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AccountCreateNestedManyWithoutLossesInput } from "./AccountCreateNestedManyWithoutLossesInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { MeasureCreateNestedManyWithoutLossesInput } from "./MeasureCreateNestedManyWithoutLossesInput";
import { SzenarioWhereUniqueInput } from "../../szenario/base/SzenarioWhereUniqueInput";
@InputType()
class LossCreateInput {
  @ApiProperty({
    required: false,
    type: () => AccountCreateNestedManyWithoutLossesInput,
  })
  @ValidateNested()
  @Type(() => AccountCreateNestedManyWithoutLossesInput)
  @IsOptional()
  @Field(() => AccountCreateNestedManyWithoutLossesInput, {
    nullable: true,
  })
  accounts?: AccountCreateNestedManyWithoutLossesInput;

  @ApiProperty({
    required: false,
    type: () => MeasureCreateNestedManyWithoutLossesInput,
  })
  @ValidateNested()
  @Type(() => MeasureCreateNestedManyWithoutLossesInput)
  @IsOptional()
  @Field(() => MeasureCreateNestedManyWithoutLossesInput, {
    nullable: true,
  })
  measures?: MeasureCreateNestedManyWithoutLossesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  shortDescription?: string | null;

  @ApiProperty({
    required: false,
    type: () => SzenarioWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SzenarioWhereUniqueInput)
  @IsOptional()
  @Field(() => SzenarioWhereUniqueInput, {
    nullable: true,
  })
  szenario?: SzenarioWhereUniqueInput | null;
}
export { LossCreateInput };
