/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateLossArgs } from "./CreateLossArgs";
import { UpdateLossArgs } from "./UpdateLossArgs";
import { DeleteLossArgs } from "./DeleteLossArgs";
import { LossFindManyArgs } from "./LossFindManyArgs";
import { LossFindUniqueArgs } from "./LossFindUniqueArgs";
import { Loss } from "./Loss";
import { AccountFindManyArgs } from "../../account/base/AccountFindManyArgs";
import { Account } from "../../account/base/Account";
import { MeasureFindManyArgs } from "../../measure/base/MeasureFindManyArgs";
import { Measure } from "../../measure/base/Measure";
import { Szenario } from "../../szenario/base/Szenario";
import { LossService } from "../loss.service";

@graphql.Resolver(() => Loss)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class LossResolverBase {
  constructor(
    protected readonly service: LossService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Loss",
    action: "read",
    possession: "any",
  })
  async _lossesMeta(
    @graphql.Args() args: LossFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Loss])
  @nestAccessControl.UseRoles({
    resource: "Loss",
    action: "read",
    possession: "any",
  })
  async losses(
    @graphql.Args() args: LossFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Loss[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Loss",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Loss, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Loss",
    action: "read",
    possession: "own",
  })
  async loss(
    @graphql.Args() args: LossFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Loss | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Loss",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Loss)
  @nestAccessControl.UseRoles({
    resource: "Loss",
    action: "create",
    possession: "any",
  })
  async createLoss(
    @graphql.Args() args: CreateLossArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Loss> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Loss",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Loss"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        szenario: args.data.szenario
          ? {
              connect: args.data.szenario,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Loss)
  @nestAccessControl.UseRoles({
    resource: "Loss",
    action: "update",
    possession: "any",
  })
  async updateLoss(
    @graphql.Args() args: UpdateLossArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Loss | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Loss",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Loss"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          szenario: args.data.szenario
            ? {
                connect: args.data.szenario,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Loss)
  @nestAccessControl.UseRoles({
    resource: "Loss",
    action: "delete",
    possession: "any",
  })
  async deleteLoss(@graphql.Args() args: DeleteLossArgs): Promise<Loss | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Account])
  @nestAccessControl.UseRoles({
    resource: "Loss",
    action: "read",
    possession: "any",
  })
  async accounts(
    @graphql.Parent() parent: Loss,
    @graphql.Args() args: AccountFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Account[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Account",
    });
    const results = await this.service.findAccounts(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => [Measure])
  @nestAccessControl.UseRoles({
    resource: "Loss",
    action: "read",
    possession: "any",
  })
  async measures(
    @graphql.Parent() parent: Loss,
    @graphql.Args() args: MeasureFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Measure[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Measure",
    });
    const results = await this.service.findMeasures(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => Szenario, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Loss",
    action: "read",
    possession: "any",
  })
  async szenario(
    @graphql.Parent() parent: Loss,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Szenario | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Szenario",
    });
    const result = await this.service.getSzenario(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
