/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AccountUpdateManyWithoutLossesInput } from "./AccountUpdateManyWithoutLossesInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { MeasureUpdateManyWithoutLossesInput } from "./MeasureUpdateManyWithoutLossesInput";
import { SzenarioWhereUniqueInput } from "../../szenario/base/SzenarioWhereUniqueInput";
@InputType()
class LossUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AccountUpdateManyWithoutLossesInput,
  })
  @ValidateNested()
  @Type(() => AccountUpdateManyWithoutLossesInput)
  @IsOptional()
  @Field(() => AccountUpdateManyWithoutLossesInput, {
    nullable: true,
  })
  accounts?: AccountUpdateManyWithoutLossesInput;

  @ApiProperty({
    required: false,
    type: () => MeasureUpdateManyWithoutLossesInput,
  })
  @ValidateNested()
  @Type(() => MeasureUpdateManyWithoutLossesInput)
  @IsOptional()
  @Field(() => MeasureUpdateManyWithoutLossesInput, {
    nullable: true,
  })
  measures?: MeasureUpdateManyWithoutLossesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  shortDescription?: string | null;

  @ApiProperty({
    required: false,
    type: () => SzenarioWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SzenarioWhereUniqueInput)
  @IsOptional()
  @Field(() => SzenarioWhereUniqueInput, {
    nullable: true,
  })
  szenario?: SzenarioWhereUniqueInput | null;
}
export { LossUpdateInput };
